name: 'Setup Haskell toolchain versions'
description: 'Setup Haskell toolchain versions'
inputs:
  ghc-version:
    description: Version of GHC to install
    default: ''

  cabal-version:
    description: Version of cabal to install
    default: ''

  pacman-packages:
    description: Pacman packages to install
    default: ''

outputs:
  cabal-store:
    description: "Prefix"
    value: ${{ steps.cabal-store.outputs.cabal-store }}

runs:
  using: "composite"
  steps:
    - name: Setup GHC
      if: inputs.ghc-version != ''
      shell: bash
      run: ghcup install ghc --set ${{ inputs.ghc-version }}

    - name: Setup cabal
      if: inputs.cabal-version != ''
      shell: bash
      run: ghcup install cabal --set ${{ inputs.cabal-version }}

    - name: "WIN: Install System Dependencies via pacman (msys2)"
      if: runner.os == 'Windows' && inputs.pacman-packages != ''
      shell: 'C:/msys64/usr/bin/bash.exe -e {0}'
      run: |
         printf "::warning::pacman packages will be installed via the input-output-hk/actions/haskell workflow.\nHowever there is no need to do it here and in general it is better to just do it on your workflow using \`/usr/bin/pacman -S -noconfirm %s\`.\nWe might remove this feature soon so please do as advised.\n\nA full step you can copy-paste into your workflow would look as follows:\n\`\`\`\n    - name: \"WIN: Install System Dependencies via pacman (msys2)\"\n      if: runner.os == 'Windows'\n      shell: 'C:/msys64/usr/bin/bash.exe -e {0}'\n      run: |\n        /usr/bin/pacman -S -noconfirm %s\n\`\`\`\n" "$(echo "${{ inputs.pacman-packages }}" | head -c -1)" "$(echo "${{ inputs.pacman-packages }}" | head -c -1)"
         /usr/bin/pacman --noconfirm -S ${{ inputs.pacman-packages }}

    # Unify the computation of the cabal store directory to a single step. This makes referencing the cabal
    # store in later steps easier.
    #
    # For cabal versions prior to cabal-3.10.1.0, we know on cabal store is located in the following locations by OS:
    #
    #   Linux: /home/runner/.cabal/store
    #   MacOS: /Users/runner/.cabal/store
    #   Windows: C:\cabal\store
    #
    # However, we compute these as best be can from information cabal provides.
    #
    # For cabal versions from cabal-3.10.1.0 onwards, XDG_CONFIG_HOME determins the location of the cabal config file
    # and the cabal store.
    - name: "Setup cabal-store"
      id: cabal-store
      shell: bash
      run: |
        cabal help user-config

        if [ "$(printf "3.10\n${{ inputs.cabal-version }}" | sort --version-sort | head -n 1)" = "3.10" ] && [ -n "$XDG_CONFIG_HOME" ]; then
          echo "Using xdg-config"
          cabal_config_file="$XDG_CONFIG_HOME/cabal/config"
          echo "cabal-store=$HOME/.local/state/cabal/store" | tee -a "$GITHUB_OUTPUT"
        else
          echo "Not using xdg-config"
          cabal_config_file="$(cabal help user-config | grep -A 1 'You can edit the cabal configuration file to set defaults' | tail -n 1 | xargs)"

          echo "XDG_CONFIG_HOME=$XDG_CONFIG_HOME"
          echo "cabal_config_file=$cabal_config_file"

          if [[ '${{ runner.os }}' != 'Windows' ]]; then
            echo "cabal-store=$(dirname "$cabal_config_file")/store" | tee -a "$GITHUB_OUTPUT"
          else
            echo "cabal-store=C:\\cabal\\store" | tee -a "$GITHUB_OUTPUT"
          fi
        fi
