name: 'Setup IOG devx'
description: 'Adds a `devx` shell includes `ghc` and `cabal`'
inputs:
  platform:
    description: 'One of x86_64-linux, x86_64-darwin, aarch64-linux, aarch64-darwin'
    type: string
    default: 'x86_64-linux'

  target-platform:
    description: 'One of "" (native), "-static", "-windows" or "-js"'
    type: string
    default: ''

  compiler-nix-name:
    description: 'The version of GHC to use'
    type: string
    default: 'ghc961'

  minimal:
    description: 'Set to `false` to get hlint and hls'
    type: boolean
    default: true

  iog:
    description: 'Set to `true` to get libsodum, libsecp256k1 and libblst'
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Install Nix with good defaults
      uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.iog.io/ https://cache.zw3rk.com/ https://cache.nixos.org/
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Install jq
      shell: bash
      run: |
        curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o jq
        chmod +x jq
    - name: Download and import closure
      shell: bash
      run: |
        ${{ github.action_path }}/support/fetch-docker.sh input-output-hk/devx ${{ inputs.platform }}.${{ inputs.compiler-nix-name }}${{ inputs.target-platform }}${{ inputs.minimal == 'true' && '-minimal' || '' }}${{ inputs.iog == 'true' && '-iog' || '' }}-env | zstd -d | nix-store --import | tee store-paths.txt
        DEVX_DRV=$(tail -n 1 store-paths.txt)
        # assert that the last path is actually the 'devx' script. If not we should not push this closure
        # as it will result in us uploading broken closures, that can not be used. We expect the last path
        # to be the devx script when pulling the pseudo-docker images down, and importing it into the
        # /nix/store. If it's anything else, we'll end up with all kinds of weird behaviours.
        if [[ ! $DEVX_DRV =~ "devx" ]]; then exit 1; fi
        sudo ln -s $DEVX_DRV /usr/local/bin/devx
